"$schema" = 'https://starship.rs/config-schema.json'

# prompt
format = """$directory$git_branch$git_status$character"""
right_format = """$all"""
add_newline = false

[character]
format = "$symbol "
success_symbol = '[|>](dimmed green)'
error_symbol = '[|>](red)'
vimcmd_symbol = '[<|](bold green)'
vimcmd_replace_one_symbol = '[<|](bold purple)'
vimcmd_replace_symbol = '[<|](bold purple)'
vimcmd_visual_symbol = '[<|](bold yellow)'

[cmd_duration]
min_time = 5_000
format = '[~$duration]($style)'

[c]
format = '[$symbol($version(-$name) )]($style)'
version_format = '${raw}'

[directory]
truncation_length = 2
truncation_symbol = '../'
style = 'blue'

[cmake]
format = '[$symbol($version )]($style)'
version_format = '${major}.${minor}'

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
style = 'dimmed purple'

[git_status]
format = '([$all_status$ahead_behind]($style) )'
style = 'red'

[golang]
format = '[$symbol($version )]($style)'
version_format = '${raw}'

[lua]
format = '[$symbol($version )]($style)'
version_format = '${raw}'

[nodejs]
format = '[$symbol($version )]($style)'
version_format = '${raw}'

[odin]
format = '[$symbol($version )]($style)'

[php]
format = '[$symbol($version )]($style)'
version_format = '${raw}'

[python]
format = '[$symbol($version )]($style)'
version_format = '${raw}'

[rust]
format = '[$symbol($version )]($style)'
version_format = '${raw}'

[zig]
format = '[$symbol($version )]($style)'
version_format = '${raw}'

